# Generated by Django 3.1.7 on 2021-03-14 18:00

from django.db import migrations, models
import library_main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to=library_main.models.get_file_name)),
                ('is_visible', models.BooleanField(default=True)),
            ],
        ),
    ]
