# Generated by Django 3.1.7 on 2021-03-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_order',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
